#! /usr/bin/env sh

NOT_GIT_REPO='fatal: not a git repository (or any of the parent directories): .git'
# shellcheck disable=SC2016
GIT_EXECUTABLE_NOT_FOUND='fatal: cannot find git executable in $PATH'

if ! git --version >/dev/null 2>&1; then
	echo "$GIT_EXECUTABLE_NOT_FOUND"
	exit 1
elif ! git rev-parse --show-toplevel >/dev/null 2>&1; then
	echo "$NOT_GIT_REPO"
	exit 2
fi

get_root_dir() {
	git rev-parse --show-toplevel
}
