#! /usr/bin/env bash

NOT_GIT_REPO='fatal: not a git repository (or any of the parent directories): .git'

git status >/dev/null 2>&1
if [[ "$?" -ne 0 ]]
then
    echo "$NOT_GIT_REPO"
    exit "$?" 
fi
