#! /usr/bin/env sh
# shellcheck disable=SC1090

. "$(dirname "$0")/check-git"

get_unchanged_list() {
	git ls-files -v | grep -E '^[a-z]' | cut -f 2 -d ' '
}

FILENAME="$1"
if [ -z "$FILENAME" ]; then
	get_unchanged_list
elif get_unchanged_list | grep -q "$FILENAME"; then
	git update-index --no-assume-unchanged "$FILENAME" && get_unchanged_list
else
	git update-index --assume-unchanged "$FILENAME" && get_unchanged_list
fi
