#! /usr/bin/env bash

. "$(dirname "$0")/check-git"
FILENAME="$1"
if [[ -z "$FILENAME" ]]
then
    git ls-files -v | grep -E '^[a-z]' | cut -f 2 -d ' '
else
    git update-index --assume-unchanged "$FILENAME"
fi 
