#! /usr/bin/env bash

. "$(dirname "$0")/check-git"

HEAD_COMMIT_ID=$(git rev-parse HEAD)
CURRENT_BRANCH=$(git branch --show-current)
if [[ -z "$CURRENT_BRANCH" ]]
then
    printf '%s\n' $HEAD_COMMIT_ID
else
    printf '%s %s\n' "$HEAD_COMMIT_ID" "$CURRENT_BRANCH"
fi

